### ISSUE TITLE
Gradient stops animating when leaving settings app

### ISSUE THREAD

**Issue by theoccurrence** [Luki120/April#8]
It only starts animating again, after opening a sub menu. Animation also works when the settings app wasn't running in the background before opening.

https://github.com/Luki120/April/assets/16444679/d3fe8ce7-c4e0-4f25-9fa2-9141695842e2

iPhone 12 Pro Max, iOS 16.4, Roothide Bootstrap

EDIT: Another video that shows the bug better:

https://github.com/Luki120/April/assets/16444679/92e02694-6db7-4d9f-b751-ea9f9641d74d

On the right side the animation is frozen, while on the left side the gradient is animated.

**Comment by Luki120** [comment]
Hi, thanks for reporting this. Try the deb on this [artifact](https://github.com/Luki120/April/actions/runs/7435240552/artifacts/1152103130), should be fixed

**Comment by theoccurrence** [comment]
Thank you very much for the quick fix 🙏🏼
